# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python code formatting with black
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user black==23.7.0
    - run: black --diff .
